version: '2'
services:
  frontend:
    build: code/frontend
    volumes:
      - ./code/frontend:/code
    ports:
      - "3449:3449"
    depends_on:
      - backend
    links:
      - backend
  backend:
    build: code/backend
    command: bash -c "mix ecto.create; mix phoenix.server"
    volumes:
      - ./code/backend:/code
    ports:
      - "4001:4000"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres