version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: mix phoenix.server
    volumes:
      - ./code:/code
    working_dir: /code/actor_viz
    ports:
      - "4000:4000"
    depends_on:
      - db
    links:
      - db